services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=True
    volumes:
      - ./data:/app/data
      - ./temp:/app/temp
    networks:
      - ocr_network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - API_HOST=api
      - API_PORT=8000
      - STREAMLIT_HOST=0.0.0.0
      - STREAMLIT_PORT=8501
      - ADMIN_PASSWORD=admin123
      - USER_PASSWORD=user123
      - DEMO_PASSWORD=demo123
    volumes:
      - ./data:/app/data
      - ./temp:/app/temp
    depends_on:
      api:
        condition: service_healthy
    networks:
      - ocr_network

networks:
  ocr_network:
    driver: bridge 